version: '3.1'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: $DBPASSWORD
      POSTGRES_USER: $DBUSER
      POSTGRES_DB: $DBNAME
    ports:
      - 15432:5432
    volumes:
      - ./conf/db/init:/docker-entrypoint-initdb.d
      - ./log/db:/var/lib/postgresql

  # web:
  #   image: nginx:latest
  #   depends_on:
  #     - app
  #   ports:
  #     - 8000:80
  #   volumes:
  #     - ./conf/nginx:/etc/nginx/conf.d
  #     - ./log/nginx:/var/log/nginx

  app:
    build: .
    ports: 
      - 8000:80
    # expose:
    #   - 80
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: $DBUSER 
      DATABASE_NAME: $DBNAME
      DATABASE_PASSWORD: $DBPASSWORD
    depends_on:
      - db
    volumes:
      - .:/app
    tty: true
    stdin_open: true
